name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Install tools
      run: make tools

    - name: Install dependencies
      run: go mod download

    - name: Generate
      run: make generate

    # Skipping linting for now
    # - name: Lint
    #   run: make lint

    - name: Test
      run: make test

    - name: Build
      run: make build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bot
        path: build/bot
